name: $(BuildId)

trigger:
  branches:
    include:
      - master
      - feature/*
      - bugfix/*
    exclude:
      - release/*

variables:
  PowerShellModules: ChangelogManagement,InvokeBuild,Pester,platyPS,MarkdownToHtml,BuildHelpers,PowerShellGet
  LinkPattern: '@{FirstRelease="$env:BUILD_REPOSITORY_URI/tree/v{CUR}";NormalRelease="$env:BUILD_REPOSITORY_URI/compare/v{PREV}..v{CUR}";Unreleased="$env:BUILD_REPOSITORY_URI/compare/v{CUR}..HEAD"}'

jobs:
- template: azure-pipelines-build.yml
  parameters:
   name: linux
   vmImage: 'ubuntu-16.04'
   tempDir: /tmp
   moduleInstallOptions: -Scope CurrentUser

- template: azure-pipelines-build.yml
  parameters:
   name: macos
   vmImage: 'macOS-10.13'
   tempDir: $env:TMPDIR

- template: azure-pipelines-build.yml
  parameters:
    name: windows_w_windows_powershell
    vmImage: 'vs2017-win2016'
    tempDir: $env:TEMP
    pwsh: false

- template: azure-pipelines-build.yml
  parameters:
    name: windows_w_powershell_core
    vmImage: 'vs2017-win2016'
    tempDir: $env:TEMP