name: $(BuildId)

variables:
  PowerShellModules: ChangelogManagement,InvokeBuild,Pester,platyPS,MarkdownToHtml,BuildHelpers,PowerShellGet
  LinkPattern: '@{FirstRelease="$env:BUILD_REPOSITORY_URI/tree/v{CUR}";NormalRelease="$env:BUILD_REPOSITORY_URI/compare/v{PREV}..v{CUR}";Unreleased="$env:BUILD_REPOSITORY_URI/compare/v{CUR}..HEAD"}'

jobs:
- template: azure-pipelines-build.yml
  parameters:
   name: linux
   vmImage: 'ubuntu-latest'
   tempDir: /tmp
   moduleInstallOptions: -Scope CurrentUser

- template: azure-pipelines-build.yml
  parameters:
   name: macos
   vmImage: 'macOS-latest'
   tempDir: $env:TMPDIR

- template: azure-pipelines-build.yml
  parameters:
    name: windows_w_windows_powershell
    vmImage: 'windows-latest'
    tempDir: $env:TEMP
    pwsh: false

- template: azure-pipelines-build.yml
  parameters:
    name: windows_w_powershell_core
    vmImage: 'windows-latest'
    tempDir: $env:TEMP