name: CI
on: [push]
jobs:
  Build:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: pwsh
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        shell: [pwsh, powershell]
        exclude:
          - os: ubuntu-latest
            shell: powershell
          - os: macos-latest
            shell: powershell
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
      - name: Install Mailhog
        run: go get github.com/mailhog/MailHog
      - name: Start Mailhog (Windows)
        run: |
          Start-Process -FilePath "$env:GOBIN\MailHog" -ArgumentList "-smtp-bind-addr", "0.0.0.0:25", "-api-bind-addr", "0.0.0.0:8025", "-ui-bind-addr", "0.0.0.0:8025"
          Start-Process -FilePath "$env:GOBIN\MailHog" -ArgumentList "-smtp-bind-addr", "0.0.0.0:1025", "-api-bind-addr", "0.0.0.0:9025", "-ui-bind-addr", "0.0.0.0:9025"
          Start-Process -FilePath "$env:GOBIN\MailHog" -ArgumentList "-smtp-bind-addr", "0.0.0.0:2025", "-api-bind-addr", "0.0.0.0:10025", "-ui-bind-addr", "0.0.0.0:10025", "-auth-file", "$env:GITHUB_WORKSPACE\test\mhcreds.txt"
        if: ${{ runner.os == 'Windows' }}
      - name: Start Mailhog (macOS/Ubuntu)
        run: |
          sudo nohup MailHog -smtp-bind-addr 0.0.0.0:25 -api-bind-addr 0.0.0.0:8025 -ui-bind-addr 0.0.0.0:8025 &>/dev/null &
          sudo nohup MailHog -smtp-bind-addr 0.0.0.0:1025 -api-bind-addr 0.0.0.0:9025 -ui-bind-addr 0.0.0.0:9025 &>/dev/null &
          sudo nohup MailHog -smtp-bind-addr 0.0.0.0:2025 -api-bind-addr 0.0.0.0:10025 -ui-bind-addr 0.0.0.0:10025 -auth-file $env:GITHUB_WORKSPACE/test/mhcreds.txt &>/dev/null &
        shell: bash
        if: ${{ runner.os != 'Windows' }}
      - name: Run Pester Tests
        uses: zyborg/pester-tests-report@v1.3.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          gist_name: ${{ github.repository }}-TestResults
          gist_badge_label: Tests %PassedCount%/%TotalCount%
          gist_token: ${{ secrets.PESTER_GIST_TOKEN }}