name: Publish
on: workflow_dispatch
jobs:
  PublishToPackages:
    #needs: Test
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Publish Module to Packages
        uses: natescherer/action-publish-powershell-to-github-packages@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: packages
          path: src