name: ReleaseToTestGallery
on: 
  workflow_dispatch:
jobs:
  PublishToPoshTestGallery:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
      - name: Remove Dashes from Version
        run: |
          $CleanVersion = "${{ steps.gitversion.outputs.NuGetPreReleaseTagV2 }}" -replace "-",""
          $CleanVersion = "${{ steps.gitversion.outputs.MajorMinorPatch }}" + "-" + $CleanVersion
          Write-Host "CLEAN_VERSION=$CleanVersion" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
      - name: Update Changelog for Release
        id: changelog
        uses: natescherer/changelog-management-action@main
        with:
          mode: release
          releaseversion: ${{ env.CLEAN_VERSION }}
      - name: Update PowerShell Metadata
        uses: natescherer/update-powershell-metadata-action@main
        with:
          path: src
          version: ${{ env.CLEAN_VERSION }}
          copyright: (c) YYYY Nate Scherer. All rights reserved.
          releasenotes: ${{ steps.changelog.outputs.releasenotes }}
          functionstoexportpath: src\public
      - name: Generate Markdown Help Files
        run: |
          Install-Module -Name platyPs
          New-Item -Path "docs" -ItemType Directory  -ErrorAction SilentlyContinue | Out-Null
          Remove-Item -Path "docs\*" -Recurse -ErrorAction SilentlyContinue
          $ModulePath = (Get-ChildItem -Path "$env:GITHUB_WORKSPACE\src" -Include "*.psm1").FullName
          $ModuleName = Split-Path -Path $ModulePath -LeafBase
          Get-Module -Name $ModuleName -All | Remove-Module -Force -ErrorAction Ignore
          Import-Module -Name $ModulePath -Force -ErrorAction Stop
          New-MarkdownHelp -Module $ModuleName -OutputFolder "docs" -NoMetadata | Out-Null
      - name: Build 'out' Directory
        run: |
          Copy-Item -Path "$env:GITHUB_WORKSPACE\src" -Destination "$env:GITHUB_WORKSPACE\out" -Recurse
      - name: Create Documentation for Release
        uses: natescherer/markdown-to-html-with-github-style-action@main
        with:
          path: README.md,CHANGELOG.md,docs
          outputpath: out
          matchpathstructure: true
      - name: Publish Module to PoshTestGallery
        uses: natescherer/publish-powershell-action@main
        with:
          token: ${{ secrets.POSHTESTGALLERY_TOKEN }}
          target: testgallery
          path: out