name: ReleaseToTestGallery
on: 
  workflow_dispatch:
jobs:
  PublishToPoshTestGallery:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
      - name: Update Changelog for Release
        id: changelog
        uses: natescherer/changelog-management-action@main
        with:
          mode: release
          releaseversion: ${{ steps.gitversion.outputs.NuGetVersionV2 }}
      - name: Update PowerShell Metadata
        uses: natescherer/update-powershell-metadata-action@main
        with:
          path: src
          version: ${{ steps.gitversion.outputs.NuGetVersionV2 }}
          copyright: (c) YYYY Nate Scherer. All rights reserved.
          releasenotes: ${{ steps.changelog.outputs.releasenotes }}
      - name: Build 'out' Directory
        run: |
          New-Item -Path "$env:GITHUB_WORKSPACE\out" -Type Directory | Out-Null
          Copy-Item -Path "$env:GITHUB_WORKSPACE\src" -Destination "$env:GITHUB_WORKSPACE\out" -Recurse
          Get-ChildItem -Path "$env:GITHUB_WORKSPACE"
      - name: Create Documentation for Release
        uses: natescherer/markdown-to-html-with-github-style-action@main
        with:
          path: README.md,CHANGELOG.md
          outputpath: out
          matchpathstructure: true
      - name: Publish Module to PoshTestGallery
        uses: natescherer/publish-powershell-action@main
        with:
          token: ${{ secrets.POSHTESTGALLERY_TOKEN }}
          target: testgallery
          path: out